import type { Metadata } from "next";
import { AdminLayout } from "@/components/admin/AdminLayout";



export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
      >
        <AdminLayout>
          {children}
        </AdminLayout>
      </main>
  );
}
