import type { Metadata } from "next";
import AllClaimsLayout from "@/components/custom/layout/allClaimsLayout";



export const metadata: Metadata = {
  title: "FactCheck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <main
      >
      

        <AllClaimsLayout>
          {children}

        </AllClaimsLayout>

       
      </main>
  );
}
